# trang admin:
# list sản phẩm GET /admin/product?page=:page(có phân trang)
GET http://localhost:3001/admin/product

### search header GET /search?name=:name
GET http://localhost:3001/search?name=jean

### sản phẩm giảm giá: /product/discount
GET http://localhost:3001/product/discount

### bán chạy: /product/top-selling
GET http://localhost:3001/product/top-selling

### sản phẩm mới: /product/new
GET http://localhost:3001/product/new

### lấy sản phẩm theo loại sản phẩm: /product/category/:id
GET http://localhost:3001/product/category/2

### lấy sản phẩm theo chi tiết loại sản phẩm: /product/category-detail/:id
GET http://localhost:3001/product/category-detail/13

### lấy category
GET http://localhost:3001/category

### lấy category-detail dựa vào category
###GET http://localhost:3001/category/:id/category-detail
GET http://localhost:3001/category/3/category-detail

###refresh-token
POST  http://localhost:3001/user/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODE2MjI1NzMsImV4cCI6MTcxMzE4MDE3M30.HXsfA-MF4pDxJv5XJvQYh204Iuw0B0lpaMH8WiFx_Sk"
}


### resgister
POST  http://localhost:3001/user/register
Content-Type: application/json

{
    "email": "louis0dadtart0ggy@gmail.com",
    "password":"123456",
    "confirmPassword": "12456",
    "name": "Lê Minh Đại",
    "avatar": "avatar",
    "level": true
}

### login
POST  http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "louistart0ggy@gmail.com",
    "password":"123456"
}

###
GET   http://localhost:3001/user/test-get-list-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODE2MjIwNDMsImV4cCI6MTY4MTcwODQ0M30.uxTC21xUKB-_iU7MmIoGOxhFYVAh_YxwWojmVcB0LxM


### logout
DELETE   http://localhost:3001/user/logout
Content-Type:  application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjI0LCJpYXQiOjE2ODE4OTMxMTQsImV4cCI6MTcxMzQ1MDcxNH0.TnU-qXWsB6aVJQP1dm9MP1Y_rshM29Y8Jtxcky4rMDQ"
}